name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: PHP ${{ matrix.php }}; Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4']
        laravel: ['6', '7']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, pecl
          extensions: mongodb, redis, zip
          coverage: none

      - name: Setup Problem Matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install Dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
            composer require "laravel/framework:{{ matrix.laravel }}" --no-update --no-interaction
            composer update --no-interaction --no-progress

      - name: Execute PHPUnit
        run: vendor/bin/phpunit
